#!/bin/bash
# Update packages and install Apache and Git
yum install -y httpd 
systemctl start httpd
systemctl enable httpd
yum install git -y
sudo git clone https://github.com/Pravalika-27/seomark.git
sudo mv seomark/seomark-html/* /var/www/html/
